### PR TITLE
FUN-33 - add description to route

### PR DESCRIPTION
**Pull request by mehdignu**
Fixes #
(comma separated list of tickets/issues/bugs fixed by the PR)

## Proposed Changes

  - add description to routes - FUN-33

License: AGPLv3

### CODE REVIEW

**Comment by takeit** [comment]
@mehdignu check this scenario `features/redirect_routes/redirect_from_one_route_to_another.feature:16` and add the `"description": null,` to the expected response since that new field has been added.

**Comment by takeit** [comment]
And this test case too `SWP\Bundle\CoreBundle\Tests\Controller\ContentControllerTest::testTestLoadingRouteWithCustomTemplate`

**Comment by mehdignu** [comment]
@takeit could you please take a look here too, thanks :)

**Review by takeit — APPROVED** [review]

**Comment by takeit** [comment]
Thanks, @mehdignu !

**Pull request merged**
