### PR TITLE
Use env variables to configure oauth endpoints

### PR DESCRIPTION
**Pull request by kottkrig**
## Proposed Changes

  - Use explicit env variables for each endpoint in the oauth authentication flow

## Why was this PR needed?

The current version of the oauth flow has hard coded endpoints based on the `EXTERNAL_OAUTH_BASE_URL` variable. This made it difficult to use with oauth providers that didn't use the exact same endpoints as this reference implementation. With these new, explicit, env variables, the Publisher implementation will be easier to use with other oauth implementations.

License: AGPLv3

### CODE REVIEW

**Comment by kottkrig** [comment]
At a first glance, the remaining errors in travis-ci do not seem related to this PR. Maybe @ahilles107 have more insight in what I can do to make them pass?

**Comment by ahilles107** [comment]
Hey ;) Rebase you pr agains of 2.1 branch. It will be ok there.

**Comment by kottkrig** [comment]
I'm not sure why the commit [
1e2ce04](https://github.com/superdesk/web-publisher/pull/1113/commits/1e2ce0408327ccba9c42a3118a2deb71deb62190) is listed as a change in this PR but it should be rebased against the 2.1 branch now.

**Comment by kottkrig** [comment]
Ah I see, that commit was present in the master branch. I'll clean that up.

**Comment by ahilles107** [comment]
as you started branch from it (and it's missing in 2.1). Rebase should fix the problem ;)

**Comment by kottkrig** [comment]
There we go. Thank you for your help! 🙌

**Pull request merged**
