### PR TITLE
Update code license and pull request template to AGPLv3

### PR DESCRIPTION
**Pull request by danielhjames**
| Q             | A
| ------------- | ---
| Bug fix?      | [no]
| New feature?  | [no]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | [SWP-140]
| License       | AGPLv3

### CODE REVIEW

**Comment by takeit** [comment]
what about license in our other dependencies https://github.com/SuperdeskWebPublisher?

**Comment by danielhjames** [comment]
Hi @takeit the dependencies should bu updated too, Sava said AGPL v3 should be for everything we make.

**Comment by takeit** [comment]
could you update it too? (in the same PR) We make changes in this repository and it will be automatically updated in our other repos. Almost every bundle, component have a LICENSE file: https://github.com/superdesk/web-publisher/tree/master/src/SWP

**Comment by danielhjames** [comment]
Sure, I can do that. I noticed some projects in https://github.com/SuperdeskWebPublisher/ have LICENSE and some have LICENSE.md - should the non-ready-only projects have separate pull requests?

**Comment by takeit** [comment]
thanks! 

> should the non-ready-only projects have separate pull requests?

right, 

`SWPAnalyticsBundle` is actually not yet `read-only` (as it says in the description) so a separate PR should be made to that repo too.

**Comment by takeit** [comment]
You could also change the Pull Request template file to include AGPLv3 license instead of GPLv3: https://github.com/superdesk/web-publisher/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by danielhjames** [comment]
Thanks, I'll make separate pull requests to the other repos. The pull request template is modified in the commit above, https://github.com/superdesk/web-publisher/pull/70/commits/20a632914129d41e42b9a743054d8531493e4d7f

**Comment by takeit** [comment]
👍

**Pull request merged**
