### PR TITLE
Added missing sockets module from php Dockerfile

### PR DESCRIPTION
**Pull request by dsmackie**
| Q                         | A
| ------------------------- | ---
| Bug fix?                  | yes
| New feature?              |no
| BC breaks?                |no
| Deprecations?             | no
| Tests pass?               | yes
| Changelog update required | no
| Fixed tickets             | #741
| License                   | AGPLv3

### CODE REVIEW

**Comment by takeit** [comment]
Hey @dsmackie, 
thank you for your Pull Request.

It looks like you haven't signed our Contributor License Agreement, yet.

Before merging this PR you have to sign our full Contributor License Agreement [here.](https://www.sourcefabric.org/en/home/policies/3201/Contributor-License-Agreement.htm)

**Comment by dsmackie** [comment]
> It looks like you haven't signed our Contributor License Agreement, yet.

Done.

**Comment by takeit** [comment]
Thanks @dsmackie!

**Comment by takeit** [comment]
fixes https://github.com/superdesk/web-publisher/issues/741

**Pull request merged**
