### PR TITLE
Fdl 548 - modified date when updating a published article

### PR DESCRIPTION
**Pull request by mehdignu**
Fixes #
(comma separated list of tickets/issues/bugs fixed by the PR)

## Proposed Changes
the article's modified date should be changed according to the type of change:

- if grammar correction the modified date should not be updated.
- if republishing modified date should be updated.
  
License: AGPLv3

### CODE REVIEW

**Comment by ahilles107** [comment]
I see two changes here, can You explain both of them?

**Comment by ahilles107** [comment]
And we don't use `modifiedAt` in templates. We use `updateAt` and it's automatically updated. What we need to do here is to disable that functionality in some cases - not introduce new property controlled manually. We have something like that  here for timestampable: `SWP\Bundle\ContentBundle\EventListener\TimestampableListener`

**Comment by mehdignu** [comment]
@ahilles107 sounds good i will work on that. the other change "length" is for the images size

**Comment by ahilles107** [comment]
@mehdignu image length should be in seperate pull request so we could merge it without waiting on changes here.

**Comment by mehdignu** [comment]
alright.

**Pull request closed without merging**
