### PR TITLE
Elastic improvements

### PR DESCRIPTION
**Pull request by ahilles107**

### CODE REVIEW

**Comment by ahilles107** [comment]
@greg606 - it looks promising - can we get publisher upgraded (#infra should do it) from this branch on ewtn staging ?

**Comment by greg606** [comment]
@ahilles107 to be honest I dont know. this looks like some of the changes already introduced to ewtn prod.

**Comment by ahilles107** [comment]
This pull request combines: #1150 and #1156 on staging (via ssh) i see lat commit set to #b2264f6df96329f61d2111c815d54e57a055ae4a

**Comment by takeit** [comment]
Closed in favour of https://github.com/superdesk/web-publisher/pull/1150

**Pull request closed without merging**
