### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by actionless**
| Q             | A
| ------------- | ---
| Bug fix?      | [yes]

this time i tested it -- works fine now

### CODE REVIEW

**Comment by actionless** [comment]
why it not merged yet?

**Comment by takeit** [comment]
there are still some issues with the `docker-compose.yml`. You can't run Web Publisher when using docker on OSX. Have you tried to run it or you just checked that the config is valid when doing `docker-compose build` ? I was working on some fixes for this which I will push soon. Anyway, this can be merged as its not really related to the main issue.

**Comment by takeit** [comment]
thanks @actionless !

**Comment by actionless** [comment]
you mean there are unresolved things for os x or in general?

**Comment by takeit** [comment]
In general, I didnt test it on, for example, Ubuntu. On osx it definitely doesn't work, even if the configuration seems to be fine, the app cant be properly set up.

**Comment by actionless** [comment]
how can it be verified what it's functional?

**Comment by takeit** [comment]
Have you tried to access the Web Publisher from the IP of your docker machine in your browser, if it works ? Because the Web Publisher vendors are not being installed at all and that might be related to the volumes not working properly on OSX.

**Comment by actionless** [comment]
do i need to provide any special configuration to point to the superdesk instance?

i will try to run it tomorrow locally and do the necessary changes if needed

but even right now i am pretty concerned about the current implementation because it's mounting code to the container instead of bundling it that is not ok by me


also i would suggest to plug webpublisher project to our current Bamboo CI workflow used for other superdesk-based projects (that probably something to discuss with @hlmnrmr )

**Comment by actionless** [comment]
there are several issue atm:
1) that container hanging with `tty: true`
2) some weird problem when mount path is just "."
3) hardcoded nginx vhost
4) as i mentioned above i don't see a point of having two container for php-fpm and nginx and using mounted volume, those containers could be split into one
5) bundle application itself inside the container, composer dependencies are required part of the app so composer install should happen on container build, not run
6) sequence of commands in the Dockerfile is not cache-friendly (but it's a minor issue)

**Comment by takeit** [comment]
@actionless would have some time to take a look into it and try to fix it?

> 5) bundle application itself inside the container, composer dependencies are required part of the app so composer install should happen on container build, not run

But how we would then access files in container? Having volumes allows us to have files locally and modify them very easly while running it on container. (or I don't understand something here)

**Comment by actionless** [comment]
> would have some time to take a look into it and try to fix it?
i can but it'll be one-time fix, i recommend including webpublisher into superdesk bamboo workflow

> But how we would then access files in container? Having volumes allows us to have files locally and modify them very easly while running it on container in a very simple way. 
in superdesk we have a separate docker-compose config for that specific case (which shares the same base named `common.yml` as normal docker-compose config):
https://github.com/superdesk/superdesk/blob/master/docker/docker-compose-dev.yml

**Pull request merged**
