### PR TITLE
SWP-121 Create WebPublisher's contribution guidelines

### PR DESCRIPTION
**Pull request by takeit**
| Q             | A
| ------------- | ---
| Doc fix?      | yes
| New docs?     | yes
| Applies to    | Contributing guidelines

TODO:

- [x] - clarify email address to send security issues (security [at] superdesk.org ?)
- [x] - clarify blog url

I have added GPLv3 license to all repositories and AUTHORS.md files.

### CODE REVIEW

**Comment by hlmnrmr** [comment]
Email address doesn't exist but it will be created today. Same thing for the Blog URL.

:+1:

**Comment by takeit** [comment]
@hlmnrmr so just to clarify:

email: `security [at] superdesk.org`
blog url: `https://www.superdesk.org/blog/`

**Comment by hlmnrmr** [comment]
Yes, I confirmed those are Ok in the previous comment!

**Comment by takeit** [comment]
thanks!

**Pull request merged**
